### ISSUE TITLE
Including assets

### ISSUE THREAD

**Issue by ghost** [hirsi911/prj-rev-bwfs-dasmoto#1]
https://github.com/hirsi911/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/index.html#L6-L13

Nice job downloading the images and then writing a relative file path to them in the `img` tags. It's better to not depend on a URL that can break or just otherwise make your images unavailable.

Even better that the images are stored in their own `images` folder. This will make your project folder much more organized and maintainable.

**Comment by hirsi911** [comment]
Thank you!
